# Copyright (C) 2012 The ShenDuOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/c8860e/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/huawei/c8860e/proprietary/libaudioalsa.so:obj/lib/libaudioalsa.so \

PRODUCT_COPY_FILES += \
    vendor/huawei/c8860e/proprietary/akmd8962:system/bin/akmd8962 \
    vendor/huawei/c8860e/proprietary/akmd8975:system/bin/akmd8975 \
    vendor/huawei/c8860e/proprietary/brcm_patchram_plus:system/bin/brcm_patchram_plus \
    vendor/huawei/c8860e/proprietary/bridgemgrd:system/bin/bridgemgrd \
    vendor/huawei/c8860e/proprietary/compassd:system/bin/compassd \
    vendor/huawei/c8860e/proprietary/cust:system/bin/cust \
    vendor/huawei/c8860e/proprietary/hciattach:system/bin/hciattach \
    vendor/huawei/c8860e/proprietary/load_oemlogo:system/bin/load_oemlogo \
    vendor/huawei/c8860e/proprietary/mm-abl-daemon:system/bin/mm-abl-daemon \
    vendor/huawei/c8860e/proprietary/modempre:system/bin/modempre \
    vendor/huawei/c8860e/proprietary/netmgrd:system/bin/netmgrd \
    vendor/huawei/c8860e/proprietary/oem_rpc_svc:system/bin/oem_rpc_svc \
    vendor/huawei/c8860e/proprietary/port-bridge:system/bin/port-bridge \
    vendor/huawei/c8860e/proprietary/qmuxd:system/bin/qmuxd \
    vendor/huawei/c8860e/proprietary/rild:system/bin/rild \
    vendor/huawei/c8860e/proprietary/rmt_oeminfo:system/bin/rmt_oeminfo \
    vendor/huawei/c8860e/proprietary/rmt_storage:system/bin/rmt_storage \
    vendor/huawei/c8860e/proprietary/usbhub:system/bin/usbhub \
    vendor/huawei/c8860e/proprietary/usbhub_init:system/bin/usbhub_init \
    vendor/huawei/c8860e/proprietary/v4l2-qcamera-app:system/bin/v4l2-qcamera-app \
    vendor/huawei/c8860e/proprietary/loc_api_app:system/bin/loc_api_app \
    vendor/huawei/c8860e/proprietary/profiler_daemon:system/bin/profiler_daemon \
    vendor/huawei/c8860e/proprietary/qmiproxy:system/bin/qmiproxy \
    vendor/huawei/c8860e/proprietary/write_NV_114:system/bin/write_NV_114 \
	vendor/huawei/c8860e/proprietary/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
	vendor/huawei/c8860e/proprietary/mediaserver:system/bin/mediaserver \

PRODUCT_COPY_FILES += \
    vendor/huawei/c8860e/proprietary/camera.msm7x30.so:system/lib/hw/camera.msm7x30.so \
    vendor/huawei/c8860e/proprietary/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/huawei/c8860e/proprietary/libaudcal.so:system/lib/libaudcal.so \
    vendor/huawei/c8860e/proprietary/libaudioalsa.so:system/lib/libaudioalsa.so \
    vendor/huawei/c8860e/proprietary/libaudioeq.so:system/lib/libaudioeq.so \
    vendor/huawei/c8860e/proprietary/libauth.so:system/lib/libauth.so \
    vendor/huawei/c8860e/proprietary/libchromatix_imx074_default_video.so:system/lib/libchromatix_imx074_default_video.so \
    vendor/huawei/c8860e/proprietary/libchromatix_imx074_preview.so:system/lib/libchromatix_imx074_preview.so \
    vendor/huawei/c8860e/proprietary/libchromatix_imx074_zsl.so:system/lib/libchromatix_imx074_zsl.so \
    vendor/huawei/c8860e/proprietary/libchromatix_mt9e013_ar.so:system/lib/libchromatix_mt9e013_ar.so \
    vendor/huawei/c8860e/proprietary/libchromatix_mt9e013_default_video.so:system/lib/libchromatix_mt9e013_default_video.so \
    vendor/huawei/c8860e/proprietary/libchromatix_mt9e013_preview.so:system/lib/libchromatix_mt9e013_preview.so \
    vendor/huawei/c8860e/proprietary/libchromatix_mt9e013_video_hfr.so:system/lib/libchromatix_mt9e013_video_hfr.so \
    vendor/huawei/c8860e/proprietary/libchromatix_mt9p017_ar.so:system/lib/libchromatix_mt9p017_ar.so \
    vendor/huawei/c8860e/proprietary/libchromatix_mt9p017_default_video.so:system/lib/libchromatix_mt9p017_default_video.so \
    vendor/huawei/c8860e/proprietary/libchromatix_mt9p017_preview.so:system/lib/libchromatix_mt9p017_preview.so \
    vendor/huawei/c8860e/proprietary/libchromatix_s5k4e1_ar.so:system/lib/libchromatix_s5k4e1_ar.so \
    vendor/huawei/c8860e/proprietary/libchromatix_s5k4e1_default_video.so:system/lib/libchromatix_s5k4e1_default_video.so \
    vendor/huawei/c8860e/proprietary/libchromatix_s5k4e1_preview.so:system/lib/libchromatix_s5k4e1_preview.so \
    vendor/huawei/c8860e/proprietary/libcm.so:system/lib/libcm.so \
    vendor/huawei/c8860e/proprietary/libdiag.so:system/lib/libdiag.so \
    vendor/huawei/c8860e/proprietary/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/huawei/c8860e/proprietary/libdsm.so:system/lib/libdsm.so \
    vendor/huawei/c8860e/proprietary/libdsprofile.so:system/lib/libdsprofile.so \
    vendor/huawei/c8860e/proprietary/libdss.so:system/lib/libdss.so \
    vendor/huawei/c8860e/proprietary/libdsutils.so:system/lib/libdsutils.so \
    vendor/huawei/c8860e/proprietary/libgps.utils.so:system/lib/libgps.utils.so \
    vendor/huawei/c8860e/proprietary/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/huawei/c8860e/proprietary/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/huawei/c8860e/proprietary/libhwnv.so:system/lib/libhwnv.so \
    vendor/huawei/c8860e/proprietary/libhwrpc.so:system/lib/libhwrpc.so \
    vendor/huawei/c8860e/proprietary/libidl.so:system/lib/libidl.so \
    vendor/huawei/c8860e/proprietary/libloc_adapter.so:system/lib/libloc_adapter.so \
    vendor/huawei/c8860e/proprietary/libloc_api-rpc-qc.so:system/lib/libloc_api-rpc-qc.so \
    vendor/huawei/c8860e/proprietary/libloc_eng.so:system/lib/libloc_eng.so \
    vendor/huawei/c8860e/proprietary/libloc_ext.so:system/lib/libloc_ext.so \
    vendor/huawei/c8860e/proprietary/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/huawei/c8860e/proprietary/libmmipl.so:system/lib/libmmipl.so \
    vendor/huawei/c8860e/proprietary/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/huawei/c8860e/proprietary/libmvs.so:system/lib/libmvs.so \
    vendor/huawei/c8860e/proprietary/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/huawei/c8860e/proprietary/libnv.so:system/lib/libnv.so \
    vendor/huawei/c8860e/proprietary/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/huawei/c8860e/proprietary/liboeminfo.so:system/lib/liboeminfo.so \
    vendor/huawei/c8860e/proprietary/liboeminfodata.so:system/lib/liboeminfodata.so \
    vendor/huawei/c8860e/proprietary/liboem_rapi.so:system/lib/liboem_rapi.so \
    vendor/huawei/c8860e/proprietary/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/huawei/c8860e/proprietary/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/huawei/c8860e/proprietary/libqdi.so:system/lib/libqdi.so \
    vendor/huawei/c8860e/proprietary/libqdp.so:system/lib/libqdp.so \
    vendor/huawei/c8860e/proprietary/libqmi.so:system/lib/libqmi.so \
    vendor/huawei/c8860e/proprietary/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/huawei/c8860e/proprietary/libqueue.so:system/lib/libqueue.so \
    vendor/huawei/c8860e/proprietary/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/huawei/c8860e/proprietary/libril.so:system/lib/libril.so \
    vendor/huawei/c8860e/proprietary/libril.so:obj/lib/libril.so \
    vendor/huawei/c8860e/proprietary/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/huawei/c8860e/proprietary/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/huawei/c8860e/proprietary/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/huawei/c8860e/proprietary/libuim.so:system/lib/libuim.so \
    vendor/huawei/c8860e/proprietary/libwms.so:system/lib/libwms.so \
    vendor/huawei/c8860e/proprietary/libwmsts.so:system/lib/libwmsts.so \
    vendor/huawei/c8860e/proprietary/libshareril.so:system/lib/libshareril.so \
    vendor/huawei/c8860e/proprietary/libgemini.so:system/lib/libgemini.so \
    vendor/huawei/c8860e/proprietary/libmmjps.so:system/lib/libmmjps.so \
    vendor/huawei/c8860e/proprietary/libcneapiclient.so:system/lib/libcneapiclient.so \
    vendor/huawei/c8860e/proprietary/libcneqmiutils.so:system/lib/libcneqmiutils.so \
    vendor/huawei/c8860e/proprietary/libcneutils.so:system/lib/libcneutils.so \
    vendor/huawei/c8860e/proprietary/libwvm.so:system/lib/libwvm.so \
    vendor/huawei/c8860e/proprietary/libcommondefs.so:system/lib/libcommondefs.so \
    vendor/huawei/c8860e/proprietary/libconfigdb.so:system/lib/libconfigdb.so \
    vendor/huawei/c8860e/proprietary/libcontrast.so:system/lib/libcontrast.so \
    vendor/huawei/c8860e/proprietary/libzy_imgdenoise.so:system/lib/libzy_imgdenoise.so \
    vendor/huawei/c8860e/proprietary/libhdr.so:system/lib/libhdr.so

PRODUCT_COPY_FILES += \
    vendor/huawei/c8860e/proprietary/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    vendor/huawei/c8860e/proprietary/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/huawei/c8860e/proprietary/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/huawei/c8860e/proprietary/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/huawei/c8860e/proprietary/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/huawei/c8860e/proprietary/libGLESv2S3D_adreno200.so:system/lib/egl/libGLESv2S3D_adreno200.so \
    vendor/huawei/c8860e/proprietary/libc2d2_z180.so:system/lib/libc2d2_z180.so \
    vendor/huawei/c8860e/proprietary/libC2D2.so:system/lib/libC2D2.so \
    vendor/huawei/c8860e/proprietary/libgsl.so:system/lib/libgsl.so \
    vendor/huawei/c8860e/proprietary/libOpenVG.so:system/lib/libOpenVG.so \
    vendor/huawei/c8860e/proprietary/libsc-a2xx.so:system/lib/libsc-a2xx.so
